### ISSUE TITLE
Having a hard time with Beginner Tutorial 

### ISSUE THREAD

**Issue by Akshaykapoor** [sirensolutions/sentinl#75]
Hi,

This projects looks really amazing and i'm wanting to try it. Started following the guide, but there is very less information for me to even get a POC setup. 

I performed the following steps,

1. I did the snapshot plugin install

2. Created data set using the script defined in the beginners tutorial

3. Created a watcher rule as mentioned in the beginners tutorial 

4. No emails triggered, no issues in any of the kibana/elasticsearch logs.

The component version i've installed are,
elasticsearch - 2.4.2
kibana - 4.6.0

I see that the elasticsearch requirement is 2.3.x. I don't see that as a problem, because there is nothing in the logs. 

Can you tell what i'm missing here.

**Comment by lmangani** [comment]
Hi @Akshaykapoor the tutorial is very basic and has several assumptions we'll try to improve.

This being said, there should be logs for execution in Kibi we'd need to see, my guess is you probably just need to copy ```sentinl.json``` from your plugin directory to ```/etc/sentinl.json``` to configure the action parametes and ```enable``` it for execution.

Please attach the Kibana logs relative to the execution in order to assist.

**Comment by cherweg** [comment]
Take care of your kibana settings. If logging.quiet ist true you won´ see anything.

**Comment by Akshaykapoor** [comment]
Well i was now able to see the sentinl dashboard. I had to copy sentinl.json from the plugins dir to /etc/sentinl.json. 

@cherweg logging.quiet parameter is already set to false. 

I've set a watcher, and see the config as below, 

<img width="1191" alt="screen shot 2016-12-02 at 4 50 52 pm" src="https://cloud.githubusercontent.com/assets/2920022/20832359/eeadba58-b8af-11e6-908f-0b81ff80e826.png">


But what could be the reason for not seeing anything on Alarms tab on sentinl dashboard.

**Comment by lmangani** [comment]
Please grep the Kibana logs for sentinl logs and paste them here  __(grep -Ri sentinl /path/to/kibana.log)__
This might be a bug with the new release - performing a deep test, please standby

**Comment by Akshaykapoor** [comment]
@lmangani thanks for the prompt response. This is what i see in kibana logs.  
```
{"type":"response","@timestamp":"2016-12-02T11:29:31Z","tags":[],"pid":18181,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/list","method":"get","headers":{"host":"127.0.0.1:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"4.6.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","referer":"http://127.0.0.1:5601/app/sentinl","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"10.0.2.2","userAgent":"10.0.2.2","referer":"http://127.0.0.1:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":13,"contentLength":9},"message":"GET /api/sentinl/list 200 13ms - 9.0B"}
{"type":"log","@timestamp":"2016-12-02T11:30:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:30:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"response","@timestamp":"2016-12-02T11:30:24Z","tags":[],"pid":18181,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/example","method":"get","headers":{"host":"127.0.0.1:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"4.6.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","referer":"http://127.0.0.1:5601/app/sentinl","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"10.0.2.2","userAgent":"10.0.2.2","referer":"http://127.0.0.1:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":9,"contentLength":9},"message":"GET /api/sentinl/example 200 9ms - 9.0B"}
{"type":"response","@timestamp":"2016-12-02T11:30:24Z","tags":[],"pid":18181,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/set/interval/%7B%22from%22:%22now-4h%22,%22mode%22:%22quick%22,%22to%22:%22now%22%7D","method":"get","headers":{"host":"127.0.0.1:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"4.6.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","referer":"http://127.0.0.1:5601/app/sentinl","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"10.0.2.2","userAgent":"10.0.2.2","referer":"http://127.0.0.1:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":14,"contentLength":9},"message":"GET /api/sentinl/set/interval/%7B%22from%22:%22now-4h%22,%22mode%22:%22quick%22,%22to%22:%22now%22%7D 200 14ms - 9.0B"}
{"type":"response","@timestamp":"2016-12-02T11:30:24Z","tags":[],"pid":18181,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/list/alarms","method":"get","headers":{"host":"127.0.0.1:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"4.6.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","referer":"http://127.0.0.1:5601/app/sentinl","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"10.0.2.2","userAgent":"10.0.2.2","referer":"http://127.0.0.1:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":9,"contentLength":9},"message":"GET /api/sentinl/list/alarms 200 9ms - 9.0B"}
{"type":"log","@timestamp":"2016-12-02T11:31:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:31:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"log","@timestamp":"2016-12-02T11:32:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:32:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"log","@timestamp":"2016-12-02T11:33:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:33:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"log","@timestamp":"2016-12-02T11:34:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:34:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"log","@timestamp":"2016-12-02T11:35:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:35:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
{"type":"log","@timestamp":"2016-12-02T11:36:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T11:36:00Z","tags":["status","info","Sentinl"],"pid":18181,"message":"Condition Error for mos: ReferenceError: payload is not defined"}
```

P.S - I'd be more than happy to contribute to editing the docs. Once i have a working environment i'll   write up something.

**Comment by lmangani** [comment]
ACK this is an issue with the rebranded build - we'll push a patch shortly!

**Comment by Akshaykapoor** [comment]
@lmangani alright..just update when you have a patch ready.

**Comment by lmangani** [comment]
Issue has been fixed, will shortly push patch + new release - thanks for helping us spot this!

**Comment by Akshaykapoor** [comment]
@lmangani will give it a try and update you

**Comment by Akshaykapoor** [comment]
@lmangani probably something missing in install. This is what I get when doing a fresh install. 

```
root@precise64:/opt/kibana/bin# ./kibana plugin --install sentinl -u https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz
Installing sentinl
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by lmangani** [comment]
@Akshaykapoor new release is up, should resolve your current issue in full - please confirm when possible

**Comment by Akshaykapoor** [comment]
@lmangani The install was successful. And the error is also not present anymore. 

But i'm still unable to see any alarms on the sentinl dashboard. This time nothing in the kibana logs except for this line. 

```
{"type":"log","@timestamp":"2016-12-02T14:31:00Z","tags":["status","info","Sentinl"],"pid":18675,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-12-02T14:32:00Z","tags":["status","info","Sentinl"],"pid":18675,"message":"Executing watch: mos"}
```  

Am i missing something ?

**Comment by lmangani** [comment]
Apparently the condition is not met and the Watcher not executed

**Comment by lmangani** [comment]
Please reopen if this is still an issue using the latest version + instructions
